// Code generated by protoc-gen-go. DO NOT EDIT.
// source: role.proto

package role

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EmptyRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyRequest) Reset()         { *m = EmptyRequest{} }
func (m *EmptyRequest) String() string { return proto.CompactTextString(m) }
func (*EmptyRequest) ProtoMessage()    {}
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_role_fa1a196d714bec1c, []int{0}
}
func (m *EmptyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyRequest.Unmarshal(m, b)
}
func (m *EmptyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyRequest.Marshal(b, m, deterministic)
}
func (dst *EmptyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyRequest.Merge(dst, src)
}
func (m *EmptyRequest) XXX_Size() int {
	return xxx_messageInfo_EmptyRequest.Size(m)
}
func (m *EmptyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyRequest proto.InternalMessageInfo

type RolesReply struct {
	Roles                []*Role  `protobuf:"bytes,1,rep,name=roles" json:"roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RolesReply) Reset()         { *m = RolesReply{} }
func (m *RolesReply) String() string { return proto.CompactTextString(m) }
func (*RolesReply) ProtoMessage()    {}
func (*RolesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_role_fa1a196d714bec1c, []int{1}
}
func (m *RolesReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RolesReply.Unmarshal(m, b)
}
func (m *RolesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RolesReply.Marshal(b, m, deterministic)
}
func (dst *RolesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RolesReply.Merge(dst, src)
}
func (m *RolesReply) XXX_Size() int {
	return xxx_messageInfo_RolesReply.Size(m)
}
func (m *RolesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RolesReply.DiscardUnknown(m)
}

var xxx_messageInfo_RolesReply proto.InternalMessageInfo

func (m *RolesReply) GetRoles() []*Role {
	if m != nil {
		return m.Roles
	}
	return nil
}

type GetUserRoleRequest struct {
	UserId               int32    `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRoleRequest) Reset()         { *m = GetUserRoleRequest{} }
func (m *GetUserRoleRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRoleRequest) ProtoMessage()    {}
func (*GetUserRoleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_role_fa1a196d714bec1c, []int{2}
}
func (m *GetUserRoleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRoleRequest.Unmarshal(m, b)
}
func (m *GetUserRoleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRoleRequest.Marshal(b, m, deterministic)
}
func (dst *GetUserRoleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRoleRequest.Merge(dst, src)
}
func (m *GetUserRoleRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRoleRequest.Size(m)
}
func (m *GetUserRoleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRoleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRoleRequest proto.InternalMessageInfo

func (m *GetUserRoleRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type Role struct {
	Id                   int32    `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Role) Reset()         { *m = Role{} }
func (m *Role) String() string { return proto.CompactTextString(m) }
func (*Role) ProtoMessage()    {}
func (*Role) Descriptor() ([]byte, []int) {
	return fileDescriptor_role_fa1a196d714bec1c, []int{3}
}
func (m *Role) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Role.Unmarshal(m, b)
}
func (m *Role) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Role.Marshal(b, m, deterministic)
}
func (dst *Role) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Role.Merge(dst, src)
}
func (m *Role) XXX_Size() int {
	return xxx_messageInfo_Role.Size(m)
}
func (m *Role) XXX_DiscardUnknown() {
	xxx_messageInfo_Role.DiscardUnknown(m)
}

var xxx_messageInfo_Role proto.InternalMessageInfo

func (m *Role) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Role) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UserRoleReply struct {
	UserId               int32    `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Roles                []*Role  `protobuf:"bytes,2,rep,name=roles" json:"roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRoleReply) Reset()         { *m = UserRoleReply{} }
func (m *UserRoleReply) String() string { return proto.CompactTextString(m) }
func (*UserRoleReply) ProtoMessage()    {}
func (*UserRoleReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_role_fa1a196d714bec1c, []int{4}
}
func (m *UserRoleReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRoleReply.Unmarshal(m, b)
}
func (m *UserRoleReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRoleReply.Marshal(b, m, deterministic)
}
func (dst *UserRoleReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRoleReply.Merge(dst, src)
}
func (m *UserRoleReply) XXX_Size() int {
	return xxx_messageInfo_UserRoleReply.Size(m)
}
func (m *UserRoleReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRoleReply.DiscardUnknown(m)
}

var xxx_messageInfo_UserRoleReply proto.InternalMessageInfo

func (m *UserRoleReply) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserRoleReply) GetRoles() []*Role {
	if m != nil {
		return m.Roles
	}
	return nil
}

func init() {
	proto.RegisterType((*EmptyRequest)(nil), "role.EmptyRequest")
	proto.RegisterType((*RolesReply)(nil), "role.RolesReply")
	proto.RegisterType((*GetUserRoleRequest)(nil), "role.GetUserRoleRequest")
	proto.RegisterType((*Role)(nil), "role.Role")
	proto.RegisterType((*UserRoleReply)(nil), "role.UserRoleReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RolesClient is the client API for Roles service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RolesClient interface {
	GetRoles(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*RolesReply, error)
	GetUserRoles(ctx context.Context, in *GetUserRoleRequest, opts ...grpc.CallOption) (*UserRoleReply, error)
}

type rolesClient struct {
	cc *grpc.ClientConn
}

func NewRolesClient(cc *grpc.ClientConn) RolesClient {
	return &rolesClient{cc}
}

func (c *rolesClient) GetRoles(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*RolesReply, error) {
	out := new(RolesReply)
	err := c.cc.Invoke(ctx, "/role.Roles/GetRoles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rolesClient) GetUserRoles(ctx context.Context, in *GetUserRoleRequest, opts ...grpc.CallOption) (*UserRoleReply, error) {
	out := new(UserRoleReply)
	err := c.cc.Invoke(ctx, "/role.Roles/GetUserRoles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RolesServer is the server API for Roles service.
type RolesServer interface {
	GetRoles(context.Context, *EmptyRequest) (*RolesReply, error)
	GetUserRoles(context.Context, *GetUserRoleRequest) (*UserRoleReply, error)
}

func RegisterRolesServer(s *grpc.Server, srv RolesServer) {
	s.RegisterService(&_Roles_serviceDesc, srv)
}

func _Roles_GetRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RolesServer).GetRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/role.Roles/GetRoles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RolesServer).GetRoles(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Roles_GetUserRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RolesServer).GetUserRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/role.Roles/GetUserRoles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RolesServer).GetUserRoles(ctx, req.(*GetUserRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Roles_serviceDesc = grpc.ServiceDesc{
	ServiceName: "role.Roles",
	HandlerType: (*RolesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRoles",
			Handler:    _Roles_GetRoles_Handler,
		},
		{
			MethodName: "GetUserRoles",
			Handler:    _Roles_GetUserRoles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "role.proto",
}

func init() { proto.RegisterFile("role.proto", fileDescriptor_role_fa1a196d714bec1c) }

var fileDescriptor_role_fa1a196d714bec1c = []byte{
	// 230 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0xb7, 0xb1, 0x5d, 0xf5, 0xb9, 0x2e, 0x32, 0x1e, 0x0c, 0x7b, 0x2a, 0x39, 0x2d, 0x82,
	0x3d, 0xd4, 0x1f, 0xe0, 0x49, 0x16, 0x3d, 0x06, 0x3c, 0x8b, 0x92, 0x39, 0x14, 0xba, 0xa6, 0x26,
	0xd9, 0x43, 0xc1, 0x1f, 0x2f, 0x49, 0x0e, 0xad, 0x48, 0x6f, 0x93, 0xbc, 0x6f, 0x1e, 0xef, 0x0d,
	0xe0, 0x6c, 0xcf, 0xcd, 0xe0, 0x6c, 0xb0, 0x54, 0xc6, 0x59, 0x6d, 0xb1, 0x79, 0x3e, 0x0e, 0x61,
	0xd4, 0xfc, 0x7d, 0x62, 0x1f, 0x54, 0x03, 0x68, 0xdb, 0xb3, 0xd7, 0x3c, 0xf4, 0x23, 0xd5, 0xa8,
	0x22, 0xe5, 0x65, 0x51, 0x9f, 0xed, 0xaf, 0x5a, 0x34, 0x69, 0x3f, 0x02, 0x3a, 0x0b, 0xea, 0x01,
	0x74, 0xe0, 0xf0, 0xe6, 0xd9, 0xa5, 0xdf, 0xec, 0x42, 0x77, 0x38, 0x3f, 0x79, 0x76, 0xef, 0x9d,
	0x91, 0x45, 0x5d, 0xec, 0x2b, 0xbd, 0x8e, 0xcf, 0x17, 0xa3, 0xee, 0x51, 0x46, 0x8e, 0xb6, 0x10,
	0x9d, 0x91, 0x22, 0x69, 0xa2, 0x33, 0x44, 0x28, 0xbf, 0x3e, 0x8e, 0x9c, 0xe8, 0x4b, 0x9d, 0x66,
	0xf5, 0x8a, 0xeb, 0xc9, 0x37, 0xa6, 0x59, 0x72, 0x9d, 0x62, 0x8a, 0x85, 0x98, 0xed, 0x0f, 0xaa,
	0x54, 0x8b, 0x5a, 0x5c, 0x1c, 0x38, 0xe4, 0x99, 0x32, 0x37, 0xef, 0xbf, 0xbb, 0x99, 0x76, 0xf3,
	0x0d, 0xd4, 0x8a, 0x9e, 0xb0, 0x99, 0x75, 0xf4, 0x24, 0x33, 0xf3, 0xbf, 0xf7, 0xee, 0x36, 0x2b,
	0x7f, 0x62, 0xab, 0xd5, 0xe7, 0x3a, 0x5d, 0xfc, 0xf1, 0x37, 0x00, 0x00, 0xff, 0xff, 0xa5, 0x64,
	0xaa, 0xf4, 0x7f, 0x01, 0x00, 0x00,
}
